# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sum.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sum.proto',
  package='sum',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tsum.proto\x12\x03sum\"\x1d\n\x0eRequestMessage\x12\x0b\n\x03num\x18\x01 \x01(\x05\"\x1b\n\x0cReplyMessage\x12\x0b\n\x03sum\x18\x01 \x01(\x05\x32G\n\nSumService\x12\x39\n\tSumServer\x12\x13.sum.RequestMessage\x1a\x11.sum.ReplyMessage\"\x00(\x01\x30\x01\x62\x06proto3'
)




_REQUESTMESSAGE = _descriptor.Descriptor(
  name='RequestMessage',
  full_name='sum.RequestMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='num', full_name='sum.RequestMessage.num', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=47,
)


_REPLYMESSAGE = _descriptor.Descriptor(
  name='ReplyMessage',
  full_name='sum.ReplyMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sum', full_name='sum.ReplyMessage.sum', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=76,
)

DESCRIPTOR.message_types_by_name['RequestMessage'] = _REQUESTMESSAGE
DESCRIPTOR.message_types_by_name['ReplyMessage'] = _REPLYMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestMessage = _reflection.GeneratedProtocolMessageType('RequestMessage', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTMESSAGE,
  '__module__' : 'sum_pb2'
  # @@protoc_insertion_point(class_scope:sum.RequestMessage)
  })
_sym_db.RegisterMessage(RequestMessage)

ReplyMessage = _reflection.GeneratedProtocolMessageType('ReplyMessage', (_message.Message,), {
  'DESCRIPTOR' : _REPLYMESSAGE,
  '__module__' : 'sum_pb2'
  # @@protoc_insertion_point(class_scope:sum.ReplyMessage)
  })
_sym_db.RegisterMessage(ReplyMessage)



_SUMSERVICE = _descriptor.ServiceDescriptor(
  name='SumService',
  full_name='sum.SumService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=78,
  serialized_end=149,
  methods=[
  _descriptor.MethodDescriptor(
    name='SumServer',
    full_name='sum.SumService.SumServer',
    index=0,
    containing_service=None,
    input_type=_REQUESTMESSAGE,
    output_type=_REPLYMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SUMSERVICE)

DESCRIPTOR.services_by_name['SumService'] = _SUMSERVICE

# @@protoc_insertion_point(module_scope)
