# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import sum_pb2 as sum__pb2


class SumServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SumServer = channel.stream_stream(
                '/sum.SumService/SumServer',
                request_serializer=sum__pb2.RequestMessage.SerializeToString,
                response_deserializer=sum__pb2.ReplyMessage.FromString,
                )


class SumServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SumServer(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SumServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SumServer': grpc.stream_stream_rpc_method_handler(
                    servicer.SumServer,
                    request_deserializer=sum__pb2.RequestMessage.FromString,
                    response_serializer=sum__pb2.ReplyMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sum.SumService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SumService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SumServer(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/sum.SumService/SumServer',
            sum__pb2.RequestMessage.SerializeToString,
            sum__pb2.ReplyMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
